# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 135ff5bbd7a7f4d80723f7f5e633d52b18f673e3de465f4425eb1d124fd162596cde971df2c026ec91b44ea30f7be2c11cf172259928c4f0ca254f4dba69cd06

test:
  secret_key_base: 66e0f36b8615f36ac19c7b4bc9ad4dbba776530cfbedd4d19032294916fbc3b71b5dabcd33b6c9dc453ecef23066789bb62961f86a8768d60cc7def980b14b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
